# Generated by Django 5.0.2 on 2024-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(max_length=100),
        ),
    ]
