# Generated by Django 5.0.2 on 2024-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_product_composition_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(max_length=300),
        ),
    ]
