# Generated by Django 5.0.2 on 2024-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TY', 'Toys1'), ('LY', 'Toys2'), ('MY', 'Toys3'), ('SY', 'Toys4'), ('VY', 'Toys5'), ('XY', 'Toys6')], max_length=100),
        ),
    ]
