# Generated by Django 5.0.1 on 2024-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_fname_register_username_remove_register_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
