# Generated by Django 5.0.1 on 2024-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_register_id_alter_profile_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
