# Generated by Django 5.0.1 on 2024-04-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='fname',
        ),
    ]
