# Generated by Django 5.0.1 on 2024-04-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_registration_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='username',
        ),
    ]
