# Generated by Django 5.0.1 on 2024-05-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_fname_registration_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
