# Generated by Django 5.0.1 on 2024-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Toys1', 'Toys1'), ('Toys2', 'Toys2'), ('Toys3', 'Toys3'), ('Toys4', 'Toys4')], max_length=100),
        ),
    ]
